### ISSUE TITLE
Theme

### ISSUE THREAD

**Issue by HeathJHMoore** [nss-evening-cohort-9/foundations-group-project-citra-a-down#1]

**Comment by samueltrejo** [comment]
color pallette theme

.dark-primary-color    { background: #E64A19; }
.default-primary-color { background: #FF5722; }
.light-primary-color   { background: #FFCCBC; }
.text-primary-color    { color: #FFFFFF; }
.accent-color          { background: #4CAF50; }
.primary-text-color    { color: #212121; }
.secondary-text-color  { color: #757575; }
.divider-color         { border-color: #BDBDBD; }
