### ISSUE TITLE
footer

### ISSUE THREAD

**Issue by matthewaustinbell** [nss-evening-cohort-9/foundations-group-project-citra-a-down#10]
# User Story
As a user, when I open any page, I should see a footer at the bottom of the page. I should see a logo and a rights reserved statement in the center of the footer

# Acceptance Criteria
**WHEN** I open any page
**THEN** I should see a footer with a logo and a right reserved centered within in it

# Development
* Add a bootstrap footer element
* Add our dope logo as an image
* Add an all rights reserved statement under the logo
* Center footer contents
* Add footer to all pages

**Comment by matthewaustinbell** [comment]
![image](https://user-images.githubusercontent.com/47642477/55044528-b3528180-5008-11e9-8f08-65fa10b03429.png)

**Comment by zoeames** [comment]
👍
