### ISSUE TITLE
Array of Beers

### ISSUE THREAD

**Issue by matthewaustinbell** [nss-evening-cohort-9/foundations-group-project-citra-a-down#11]
# User Story
As a developer, I should see an array of objects containing beer information. Each object should contain the following key-value pairs: Name, Style, Image, Ingredients, IBU, and Gravity. The ingredients key should have a value that is an array of ingredients composing the beer.

# AC
**When** I open the main.js file,
**Then** I will see an array of objects `arrayOfBeers`
**And** a console.log that returns the array.

# Development
* Create an array of objects and name it arrayOfBeers
* Each object should contain the following key-value pairs: Name, Style, Image, Ingredients, IBU, Gravity
* The ingredients key-value should be an array of ingredients

**Comment by zoeames** [comment]
need more info here
