### ISSUE TITLE
About Us - Contact Us Section

### ISSUE THREAD

**Issue by HeathJHMoore** [nss-evening-cohort-9/foundations-group-project-citra-a-down#13]
# User Story
As a user, when I open the About Us page, I should see a contact us section with a form. Upon submitting the form, a modal should appear thanking me for my inquiry.

# AC
**WHEN** I open the About Us page
**THEN** I should see a contact us section 
**AND** a contact us form that opens a thank you modal upon submission

# Development
* Create a Contact us `<h1>` element below the team member cards
* Create a `<div>` element below the Contact Us header. 
* This div will contain a `<p>` element describing why you might want to contact us about business inquires and careers
* This div will also contain a bootstrap form. This form should contain a submit button and 3 input elements: Name, Email, and Message.
* Create a modal that appears on form submission that thanks the user for their inquiry.

**Comment by HeathJHMoore** [comment]
![image](https://user-images.githubusercontent.com/47693976/55201191-deb3a880-518f-11e9-8b90-50494ce54181.png)

**Comment by zoeames** [comment]
👍
