### ISSUE TITLE
Our Beers Page - Beer Cards

### ISSUE THREAD

**Issue by HeathJHMoore** [nss-evening-cohort-9/foundations-group-project-citra-a-down#14]
# User Story
As a user, when I open the Our Beers Page, I should see a bunch of cards showcasing and describing our beers.

# Acceptance Criteria
**WHEN** I open the Our Beers Page,
**THEN** I should see a bunch of cards showcasing and describing our beers.

# Development
* If printToDom function or domStringBuilder function does not exist, reference ticket #3 for instructions on how to make these functions
* Using domStringBuilder, Create a domString that builds a bootstrap card by iterating through 6 key value pairs of each object in the array of beers (#11 ): An `<h2>` Name element, an image tag, and `<p>` elements for the style, ingredients, IBU, and gravity.
* domStringBuilder should call printToDom to print each beer card to the DOM.

**Comment by zoeames** [comment]
wireframe?

**Comment by samueltrejo** [comment]
wireframe for beers section in our beers page

![image](https://user-images.githubusercontent.com/47835231/55276859-ca25fc00-52c6-11e9-93b5-eed3ca30bd0e.png)

**Comment by zoeames** [comment]
👍
