### ISSUE TITLE
Our Beers - Sort Event

### ISSUE THREAD

**Issue by HeathJHMoore** [nss-evening-cohort-9/foundations-group-project-citra-a-down#15]
# User Story
As a user, when load the page I should see all of the beers. And clicking the sort buttons should show me only the beers with the type of the button that I clicked on.

# AC
**WHEN** I load the page
**THEN** all beers should show
**AND** if sort buttons are pressed
**THEN** I should see the appropriate beers displayed that match the button type 

# Development
* add id's to the sort buttons: ales, loggers, wheat, specialty
* Make a addButtonEvents function that adds event listeners to the category buttons
* The category buttons will call the sort function,
* The sort function will iterate over array of beers, and check if the id of the press button, matches the style value in the beer object and add it to a newBeersArray
* the sort function will then call the domStringBuilder function passing in the newBeersArray

**Comment by zoeames** [comment]
👍
