### ISSUE TITLE
Six Pack Page - Jumbotron Header

### ISSUE THREAD

**Issue by samueltrejo** [nss-evening-cohort-9/foundations-group-project-citra-a-down#16]
# User Story
As a user, when I load the Create Your Own Six Pack page, I should see the heading, and a list of our beers

# AC
**WHEN** I load the page
**THEN** A jumbotron should appear with the page heading
AND** A subsection with our beers heading and a list of all of our beer

# Development
* Create a bootstrap fluid jumbotron, with a div holding our beers heading, and a list of all of our beer
* The main jumbotron heading will be Create Your Own Six Pack

**Comment by zoeames** [comment]
👍
