### ISSUE TITLE
Six Pack Page - Create Six Pack

### ISSUE THREAD

**Issue by samueltrejo** [nss-evening-cohort-9/foundations-group-project-citra-a-down#17]

**Comment by JenniferLipps** [comment]
# User Story

As a user, when I type a beer name in the input field, the beer is added to the six pack.

# AC

**When** I open the Create Your Own Six Pack page, I see the list of available beer names and an input.
**And When** I type the beer name in the input,
**Then** the beer is added to a card in the six pack area of the page.

# Development

* Make a `sixPack` array, which is empty on page load.
* Create an `addBeer` function that makes an object with 1 key/value pair. The key will be `beer` and the value will be what came from the input. That object will `.push` into the `sixPack` array. Call `beerStringBuilder` function and pass `sixPack`.
* Add a `beerStringBuilder` function which has 1 input, `sixPack`.
* The `beerStringBuilder` function should loop over `sixPack` and build a domstring of bootstrap cards (add class col-3). The cards include a Delete button. It should then pass this string to `printToDom` function.

**Comment by zoeames** [comment]
👍
