### ISSUE TITLE
Delete a Beer from Six Pack

### ISSUE THREAD

**Issue by JenniferLipps** [nss-evening-cohort-9/foundations-group-project-citra-a-down#18]

**Comment by JenniferLipps** [comment]
# User Story

As a user, when I click the Delete button on a beer in the six pack, the beer is removed from the six pack.

# AC

**When** the Delete button is pressed,
**Then** the beer disappears from the six pack.

# Development

* Add a counter called `beerCounter`. This will be set to 1 on page load.
* Modify the object created in the `addBeer` function to add a key/value pair. The key is `id` and the value is `beer${beerCounter}`.
* Add a class of deleteButton to the delete buttons on the cards and add an id = beer.id
* Write a for loop to loop over all delete buttons, add eventListener to each button that calls a function called `addDeleteEvents`.
* Select all of the delete buttons using `getElementsByClassName`. Add eventListener that calls a function `deleteFunction` on click.
* Create function `deleteFunction` which contains a forEach loop to loop over `sixPack`. `deleteFunction` should take 1 input: event, compare e.target.id to the `sixPack` array (forEach loop and an if statement).  When If statement is true, splice the current itemin the forEach loop, call domStringBuilder, and pass in `sixPack` array. Re-attach the delete button events to the remaining cards.

**Comment by zoeames** [comment]
👍
