### ISSUE TITLE
Home Page - Our Beers Carousel

### ISSUE THREAD

**Issue by HeathJHMoore** [nss-evening-cohort-9/foundations-group-project-citra-a-down#19]
# User Story
As a user, when I launch the Home Page, I should see a carousel of images of beer. The carousel should have arrows that I can click to browse through the images. Each image should also have a caption.

# AC
**WHEN** I launch the Home Page
**THEN** I should see a carousel of images of beers 
**AND** the carousel should have arrows I can click to the browse through the images
**AND** each image should have a caption

# Development
* Below the About Us section, add a bootstrap carousel with captions (Reference comment below for code snippet) 
* Create 5 `<div class="carousel-item">` elements within the bootstrap carousel code
* Add a caption to each carousel item by adding the following code snippet to each `<div class="carousel-item">`:
```html
  <div class="carousel-caption d-none d-md-block">
    <h5>...</h5>
    <p>...</p>
  </div>
```

**Comment by HeathJHMoore** [comment]
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img class="d-block w-100" src="..." alt="First slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="..." alt="Second slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="..." alt="Third slide">
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

**Comment by HeathJHMoore** [comment]
```html
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img class="d-block w-100" src="..." alt="First slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="..." alt="Second slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="..." alt="Third slide">
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
```

**Comment by JenniferLipps** [comment]
Image links:

https://cdn.pixabay.com/photo/2018/11/08/22/12/beer-3803425_960_720.jpg

http://mudsharkbeer.com/wp-content/uploads/2017/07/18489467_10155220337021897_9109165530661672208_o.jpg

https://cdn.pixabay.com/photo/2016/06/18/15/48/beer-1465153_960_720.jpg

https://cdn.pixabay.com/photo/2018/02/13/18/21/beer-bottles-3151245_960_720.jpg

**Comment by zoeames** [comment]
👍
