### ISSUE TITLE
Home Page - About Us

### ISSUE THREAD

**Issue by samueltrejo** [nss-evening-cohort-9/foundations-group-project-citra-a-down#20]
# User Story
As user when I load the home page, I should see an about us section with short description, company staff pic and a button that takes me to about-us.html

# AC
**WHEN** I open the home page
**THEN** I should see an about us page with description, company photo and button
**AND** The about us button should take me to the about-us.html page

# Development
* Create a container div, with an id of `about us`
* about us/ container div should contain a description on the left
* about us/ container div should contain on the right: a heading, company image, and a button that links to about-us.html 'reference wireframe'

**Comment by samueltrejo** [comment]
home page, about us section wireframe

![image](https://user-images.githubusercontent.com/47835231/55277412-e4afa380-52cd-11e9-82c7-49244f3933df.png)

**Comment by zoeames** [comment]
👍
