### ISSUE TITLE
About Page - About Us and Cards

### ISSUE THREAD

**Issue by HeathJHMoore** [nss-evening-cohort-9/foundations-group-project-citra-a-down#3]
# User Story
As a user, when I open the About Us page, I should see an About us section describing the company along with 4 cards describing each team member

# Acceptance Criteria
**WHEN** I open the About us page
**THEN** I should see an About us section with a description of the company
 **AND** 4 cards describing each team member

# Development
* Add a `<div id="aboutus-description">` element that will contain a `<h1>` element saying "About Us" and a `<p>` element providing a description of who we are and how awesome we are
* In the main.js file, create a printToDom function that takes two arguments: divID and textToPrint. This function should have the ability to print the About Us cards to a div underneath the `<div id="aboutus-description>` element
* In the main.js file, create a domStringBuilder function that takes an array as an argument. This function should create a domString that can be passed as a textToPrint argument in the printToDom function. 
* The domString in domStringBuilder should build a card (`<div class="card">`) that contains an `<h3>` element with each person's name, an image of each person, and a `<p>` element with a brief description of each person.

**Comment by HeathJHMoore** [comment]
![image](https://user-images.githubusercontent.com/47693976/55042657-826e4e80-5000-11e9-9410-3c0310b427cf.png)

**Comment by HeathJHMoore** [comment]
![image](https://user-images.githubusercontent.com/47693976/55042777-22c47300-5001-11e9-9322-af0abf7a62cc.png)

**Comment by zoeames** [comment]
👍
