### ISSUE TITLE
Home Page - Jumbotron

### ISSUE THREAD

**Issue by HeathJHMoore** [nss-evening-cohort-9/foundations-group-project-citra-a-down#5]
# User Story
As a user, when I open the home page, I should see a jumbotron that welcomes me to the page and has 3 buttons

# Acceptance Criteria
**WHEN** I open the home page
**THEN**  I should see a jumbotron that welcomes me to the page 
**AND** the jumbotron should have 3 buttons in it

# Development
* Add a bootstrap fluid jumbotron as the first section (dont worry about the navbar, there is a separate ticket for that). 
* Add a background-image to the jumbotron (pick whatever picture you want, just make sure it has beer in it)
* Add a `<h1>` element that says "Welcome"
* Add a `<p>` element below the Welcome heading that says "A Nashville Original since 2019".
* Add a `<div>` below the `<p>` element. This div should contain 3 buttons titled the following: About, Our Beers, Create Six Pack.
* Buttons should link to their respective container divs with ids, about-us, our-beers, and six-pack

**Comment by HeathJHMoore** [comment]
![image](https://user-images.githubusercontent.com/47693976/55042754-fd376980-5000-11e9-8890-c80159dcb2a4.png)

**Comment by HeathJHMoore** [comment]
```html
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">Fluid jumbotron</h1>
    <p class="lead">This is a modified jumbotron that occupies the entire horizontal space of its parent.</p>
  </div>
</div>
```

**Comment by zoeames** [comment]
👍
