### ISSUE TITLE
Our Beers Page - Our Beers Introduction and Sorting Buttons

### ISSUE THREAD

**Issue by HeathJHMoore** [nss-evening-cohort-9/foundations-group-project-citra-a-down#6]
# User Story
As a user, when I open the Our Beers page, I should see a "Our Beers" header, a description of how great our beers are, and 5 buttons

# AC
**WHEN** I open the Our Beers page
**THEN** I should see an "Our Beers" header
**AND** a description of our beers
**AND** 5 buttons

# Development
* Create a `<div>` element that contains an `<h1>` "Our Beers" element and a `<p>` element that describes how great and how craft our beers are.
* Below the previous div, Create a new `<div>` that contains 5 button elements: All, Ales, Lagers, Wheat Beers, Specialty Beers
* Reference the below wireframe for styling and positioning

**Comment by HeathJHMoore** [comment]
![image](https://user-images.githubusercontent.com/47693976/55043115-987d0e80-5002-11e9-87fa-d5d7b287ddf8.png)

**Comment by zoeames** [comment]
👍
