### ISSUE TITLE
Setup

### ISSUE THREAD

**Issue by HeathJHMoore** [nss-evening-cohort-9/foundations-group-project-citra-a-down#8]
# User story 
as a user, in order to DO ALL the things i need some starter code

# AC
**when** page loads then 
**then**,  the background color should be pink
**and** there should be a large hi 
**and** there god be a console log that says ‘’moooooooooooo’’
**and** there should be a red bootstrap button that says hi

# development 
* index. html- with boiler plate html
* pages directory - contains all html pages aside from index.html
* main.js- with a console.log
* main.css with a background color change on the body ‘
* add a link for the bootstrap

**Comment by zoeames** [comment]
👍
