### ISSUE TITLE
navbar

### ISSUE THREAD

**Issue by matthewaustinbell** [nss-evening-cohort-9/foundations-group-project-citra-a-down#9]
# User Story
As a user, when I open any page, I should see a nav bar at the top of the page with a logo, social media buttons, and page navigation buttons. The nav bar should stick to the top of the page on scroll

# AC
**WHEN** I open any page
**THEN** I should a nav at the top of the page with a logo, social media buttons, and page navigation buttons 
**AND** I should be able to click on the social media buttons, taking me to their respecitve web locaitons
**AND** I should be able to click on the page navigation buttons, taking me to the respective pages of the website
**AND** the nav bar should stick to the top of the window on scroll

# Development
* Start by adding a bootstrap nav bar element
* Add 4 page navigation buttons to the right of the nav bar: Home, About, Our Beers, Events
* Add links to the 4 navigations buttons so that each button takes the user to the appropriate page
* Add dope logo to the top left of the nav bar
* Add 3 social media buttons immediately to the right of the logo for the following sites: Facebook, 
Instagram, Twitter
* Add links to the 3 social media buttons so that each button takes the user to the appropriate social media site
* Add a class of `sticky-top` to the navbar
* Apply nav bar element to html file of every page

**Comment by matthewaustinbell** [comment]
```html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Features</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Pricing</a>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
      </li>
    </ul>
  </div>
</nav>
```

**Comment by matthewaustinbell** [comment]
![image](https://user-images.githubusercontent.com/47642477/55044497-88682d80-5008-11e9-8cb8-882b6a0af30e.png)

**Comment by zoeames** [comment]
👍
